//! Canonical, fixed-point curated-manifest generation.

use std::{error::Error, fmt};

use crate::{
    AabbQ8, CUT_STONE, CuratedManifest, FeatureInstance, FeatureKind, ObjectId, ObjectIndexConfig,
    ObjectKind, ObjectPlacement, QuantizedTransform, RegionConfig, RouteTag, RouteWaypoint,
    RuinPoi, SparseVoxelStamp, SpeciesId, VoxelCoord, VoxelObjectShape, WaterBodyDef, WaterKind,
    WorldPointQ8, build_object_index, parameters_digest_from_bytes,
    validate_object_shape_disjointness, validate_region_config,
};

use super::ManifestError;

const GENERATED_FILE_COMMENT: &str = "// Generated by moria-curate generate; DO NOT EDIT.\n";
const FOREST_AREA_M2: u32 = 120_000;
const ELIGIBLE_LAND_AREA_M2: u32 = 120_000;
const TREE_SPACING_METERS: i32 = 9;
const SURFACE_Y_METERS: i32 = 64;

/// A generation failure with the input or invariant that prevented curation.
#[derive(Debug)]
pub enum CurationGenerateError {
    RegionConfig(String),
    RuinStamp(String),
    Contract(String),
}

impl fmt::Display for CurationGenerateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::RegionConfig(error) => write!(formatter, "invalid region configuration: {error}"),
            Self::RuinStamp(error) => write!(formatter, "invalid ruin stamp: {error}"),
            Self::Contract(error) => write!(formatter, "curation contract failed: {error}"),
        }
    }
}

impl Error for CurationGenerateError {}

/// Generates the complete deterministic manifest from the exact input bytes.
pub fn generate_manifest(
    region_config_bytes: &[u8],
    ruin_stamp_bytes: &[u8],
) -> Result<CuratedManifest, CurationGenerateError> {
    let config: RegionConfig = ron::de::from_bytes(region_config_bytes)
        .map_err(|error| CurationGenerateError::RegionConfig(error.to_string()))?;
    validate_region_config(&config)
        .map_err(|error| CurationGenerateError::RegionConfig(error.to_string()))?;
    let stamp: SparseVoxelStamp = ron::de::from_bytes(ruin_stamp_bytes)
        .map_err(|error| CurationGenerateError::RuinStamp(error.to_string()))?;
    stamp
        .validate()
        .map_err(|error| CurationGenerateError::RuinStamp(error.to_string()))?;

    let mut cursor = CandidateCursor::new();
    let mut next_id = 1_u64;
    let tree_count = ceil_div(FOREST_AREA_M2, 25);
    let birch_count = u32::from(config.biome.tree_species_mix_percent[0]) * tree_count / 100;
    let pine_count = tree_count - birch_count;
    let mut objects = Vec::with_capacity(usize::try_from(tree_count).unwrap_or(0));
    for index in 0..tree_count {
        let birch = index < birch_count;
        objects.push(tree(
            next_id,
            cursor.next()?,
            birch,
            index == 0 || index == birch_count,
        ));
        next_id += 1;
    }
    debug_assert_eq!(birch_count + pine_count, tree_count);

    append_kind(
        &mut objects,
        &mut cursor,
        &mut next_id,
        ceil_div(
            FOREST_AREA_M2 * u32::from(config.biome.bushes_per_hectare),
            10_000,
        ),
        ObjectKind::Bush,
    )?;
    append_kind(
        &mut objects,
        &mut cursor,
        &mut next_id,
        ceil_div(
            ELIGIBLE_LAND_AREA_M2 * u32::from(config.objects.boulders_per_hectare),
            10_000,
        ),
        ObjectKind::Boulder,
    )?;
    append_kind(
        &mut objects,
        &mut cursor,
        &mut next_id,
        ceil_div(
            ELIGIBLE_LAND_AREA_M2 * u32::from(config.objects.stumps_per_hectare),
            10_000,
        ),
        ObjectKind::Stump,
    )?;
    append_kind(
        &mut objects,
        &mut cursor,
        &mut next_id,
        ceil_div(
            ELIGIBLE_LAND_AREA_M2 * u32::from(config.objects.rocks_per_hectare),
            10_000,
        ),
        ObjectKind::Rock,
    )?;

    let ruin = ruin();
    let manifest = CuratedManifest {
        seed: config.seed,
        parameters_digest: parameters_digest_from_bytes(region_config_bytes, ruin_stamp_bytes),
        generated_by: "moria-curate generate".to_owned(),
        features: vec![FeatureInstance {
            id: 1,
            kind: FeatureKind::Stratum,
            bounds: AabbQ8::new(
                WorldPointQ8::new(-128_000, -32_768, -128_000),
                WorldPointQ8::new(128_000, 32_768, 128_000),
            )
            .expect("fixed Product One bounds are valid"),
            host_material: CUT_STONE,
            depth_q8: 0,
            orientation_q16: [0, 0, 0, 65_536],
            generator_key: config.seed,
        }],
        water_bodies: vec![WaterBodyDef {
            id: 1,
            kind: WaterKind::Lake,
            surface_y_q8: SURFACE_Y_METERS * 256,
            footprint: vec![
                WorldPointQ8::new(-25_600, SURFACE_Y_METERS * 256, -25_600),
                WorldPointQ8::new(-20_480, SURFACE_Y_METERS * 256, -25_600),
                WorldPointQ8::new(-23_040, SURFACE_Y_METERS * 256, -20_480),
            ],
            bed_profile_key: config.seed,
        }],
        objects,
        ruin,
        route: vec![RouteWaypoint {
            order: 0,
            point: WorldPointQ8::new(-12_800, SURFACE_Y_METERS * 256, -12_800),
            tags: vec![RouteTag::Forest, RouteTag::SignatureCarveHillside],
        }],
    };
    validate_manifest(&manifest, &stamp)?;
    Ok(manifest)
}

/// Serializes a generated manifest using the only checked-in representation.
pub fn canonical_manifest_ron(manifest: &CuratedManifest) -> Result<String, CurationGenerateError> {
    manifest.validate().map_err(manifest_error)?;
    let options = ron::ser::PrettyConfig::new()
        .depth_limit(4)
        .separate_tuple_members(true)
        .enumerate_arrays(true);
    let body = ron::ser::to_string_pretty(manifest, options)
        .map_err(|error| CurationGenerateError::Contract(error.to_string()))?;
    Ok(format!("{GENERATED_FILE_COMMENT}{body}\n"))
}

fn validate_manifest(
    manifest: &CuratedManifest,
    stamp: &SparseVoxelStamp,
) -> Result<(), CurationGenerateError> {
    manifest.validate().map_err(manifest_error)?;
    let index = build_object_index(&manifest.objects, &ObjectIndexConfig::default())
        .map_err(manifest_error)?;
    validate_object_shape_disjointness(&index, &manifest.ruin, stamp).map_err(manifest_error)
}

fn manifest_error(error: ManifestError) -> CurationGenerateError {
    CurationGenerateError::Contract(error.to_string())
}

fn append_kind(
    objects: &mut Vec<ObjectPlacement>,
    cursor: &mut CandidateCursor,
    next_id: &mut u64,
    count: u32,
    kind: ObjectKind,
) -> Result<(), CurationGenerateError> {
    for _ in 0..count {
        objects.push(placement(*next_id, cursor.next()?, kind));
        *next_id += 1;
    }
    Ok(())
}

fn tree(id: u64, point: WorldPointQ8, birch: bool, edge_canopy: bool) -> ObjectPlacement {
    let canopy = if edge_canopy { 512 } else { 768 };
    ObjectPlacement {
        kind: if birch {
            ObjectKind::TreeA
        } else {
            ObjectKind::TreeB
        },
        species: Some(SpeciesId(if birch { 1 } else { 2 })),
        shape: VoxelObjectShape::Tree {
            trunk_radius_q8: if birch { 70 } else { 90 },
            trunk_height_q8: if birch { 2_560 } else { 3_584 },
            canopy_radii_q8: [canopy, canopy, if edge_canopy { 1_024 } else { canopy }],
        },
        ..placement_at(id, point)
    }
}

fn placement(id: u64, point: WorldPointQ8, kind: ObjectKind) -> ObjectPlacement {
    let shape = match kind {
        ObjectKind::Bush => VoxelObjectShape::Bush {
            radii_q8: [256, 192, 256],
        },
        ObjectKind::Boulder => VoxelObjectShape::Boulder {
            radii_q8: [384, 384, 384],
            perturbation_key: id,
        },
        ObjectKind::Stump => VoxelObjectShape::Stump {
            radius_q8: 96,
            height_q8: 128,
        },
        ObjectKind::Rock => VoxelObjectShape::Rock {
            radii_q8: [128, 96, 128],
            perturbation_key: id,
        },
        ObjectKind::TreeA | ObjectKind::TreeB | ObjectKind::Ruin => {
            unreachable!("handled separately")
        }
    };
    ObjectPlacement {
        kind,
        species: None,
        shape,
        ..placement_at(id, point)
    }
}

fn placement_at(id: u64, point: WorldPointQ8) -> ObjectPlacement {
    ObjectPlacement {
        id: ObjectId(id),
        kind: ObjectKind::Bush,
        transform_q: QuantizedTransform {
            translation: point,
            yaw_quarter_turns: 0,
            uniform_scale_q8: 256,
        },
        species: None,
        shape: VoxelObjectShape::Bush {
            radii_q8: [1, 1, 1],
        },
        anchor: VoxelCoord::new(point.x / 64, point.y / 64, point.z / 64),
    }
}

fn ruin() -> RuinPoi {
    let point = WorldPointQ8::new(0, SURFACE_Y_METERS * 256, 0);
    RuinPoi {
        placement: ObjectPlacement {
            id: ObjectId(0),
            kind: ObjectKind::Ruin,
            transform_q: QuantizedTransform {
                translation: point,
                yaw_quarter_turns: 0,
                uniform_scale_q8: 256,
            },
            species: None,
            shape: VoxelObjectShape::SparseStamp {
                asset_key: "moria.stamps.ruin_p1".to_owned(),
            },
            anchor: VoxelCoord::new(0, SURFACE_Y_METERS * 4, 0),
        },
        stair_bottom: point,
        stair_top: WorldPointQ8::new(0, (SURFACE_Y_METERS + 3) * 256, 512),
    }
}

fn ceil_div(value: u32, divisor: u32) -> u32 {
    value.div_ceil(divisor)
}

struct CandidateCursor {
    x: i32,
    z: i32,
}

impl CandidateCursor {
    const fn new() -> Self {
        Self { x: -490, z: -490 }
    }

    fn next(&mut self) -> Result<WorldPointQ8, CurationGenerateError> {
        loop {
            if self.z > 490 {
                return Err(CurationGenerateError::Contract(
                    "candidate grid cannot satisfy required placement counts".to_owned(),
                ));
            }
            let point = WorldPointQ8::new(self.x * 256, SURFACE_Y_METERS * 256, self.z * 256);
            self.x += TREE_SPACING_METERS;
            if self.x > 490 {
                self.x = -490;
                self.z += TREE_SPACING_METERS;
            }
            if point.x.abs() >= 2_560 || point.z.abs() >= 2_560 {
                return Ok(point);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{canonical_manifest_ron, generate_manifest};

    #[test]
    fn generation_is_byte_deterministic_and_uses_both_input_byte_streams() {
        let region = include_bytes!("../../../../assets/config/product_one_region.ron");
        let stamp = include_bytes!("../../../../assets/stamps/ruin_p1.ron");
        let first = generate_manifest(region, stamp).unwrap();
        let second = generate_manifest(region, stamp).unwrap();

        assert_eq!(first, second);
        assert_eq!(
            canonical_manifest_ron(&first).unwrap(),
            canonical_manifest_ron(&second).unwrap()
        );
        assert!(!first.objects.is_empty());
    }
}
