//! Canonical, fixed-point curated-manifest generation.

use std::{error::Error, fmt};

use crate::{
    AabbQ8, CUT_STONE, CuratedManifest, FeatureInstance, FeatureKind, GRANITE, IRON_ORE, ObjectId,
    ObjectIndexConfig, ObjectKind, ObjectPlacement, QuantizedTransform, RegionConfig, RouteTag,
    RouteWaypoint, RuinPoi, SparseVoxelStamp, SpeciesId, VoxelCoord, VoxelObjectShape, WATER,
    WaterBodyDef, WaterKind, WorldPointQ8, build_object_index, parameters_digest_from_bytes,
    validate_object_shape_disjointness, validate_region_config,
};

use super::ManifestError;

const GENERATED_FILE_COMMENT: &str = "// Generated by moria-curate generate; DO NOT EDIT.\n";
const FOREST_AREA_M2: u32 = 120_000;
const ELIGIBLE_LAND_AREA_M2: u32 = 120_000;
const TREE_SPACING_METERS: i32 = 9;
const SURFACE_Y_METERS: i32 = 64;

/// A generation failure with the input or invariant that prevented curation.
#[derive(Debug)]
pub enum CurationGenerateError {
    RegionConfig(String),
    RuinStamp(String),
    Contract(String),
}

impl fmt::Display for CurationGenerateError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::RegionConfig(error) => write!(formatter, "invalid region configuration: {error}"),
            Self::RuinStamp(error) => write!(formatter, "invalid ruin stamp: {error}"),
            Self::Contract(error) => write!(formatter, "curation contract failed: {error}"),
        }
    }
}

impl Error for CurationGenerateError {}

/// Generates the complete deterministic manifest from the exact input bytes.
pub fn generate_manifest(
    region_config_bytes: &[u8],
    ruin_stamp_bytes: &[u8],
) -> Result<CuratedManifest, CurationGenerateError> {
    let config: RegionConfig = ron::de::from_bytes(region_config_bytes)
        .map_err(|error| CurationGenerateError::RegionConfig(error.to_string()))?;
    validate_region_config(&config)
        .map_err(|error| CurationGenerateError::RegionConfig(error.to_string()))?;
    let stamp: SparseVoxelStamp = ron::de::from_bytes(ruin_stamp_bytes)
        .map_err(|error| CurationGenerateError::RuinStamp(error.to_string()))?;
    stamp
        .validate()
        .map_err(|error| CurationGenerateError::RuinStamp(error.to_string()))?;

    let mut cursor = CandidateCursor::new();
    let mut next_id = 1_u64;
    let tree_count = ceil_div(FOREST_AREA_M2, 25);
    let birch_count = u32::from(config.biome.tree_species_mix_percent[0]) * tree_count / 100;
    let pine_count = tree_count - birch_count;
    let mut objects = Vec::with_capacity(usize::try_from(tree_count).unwrap_or(0));
    for index in 0..tree_count {
        let birch = index < birch_count;
        objects.push(tree(
            next_id,
            cursor.next()?,
            birch,
            canopy_radius(index, birch_count),
        ));
        next_id += 1;
    }
    debug_assert_eq!(birch_count + pine_count, tree_count);

    append_kind(
        &mut objects,
        &mut cursor,
        &mut next_id,
        ceil_div(
            FOREST_AREA_M2 * u32::from(config.biome.bushes_per_hectare),
            10_000,
        ),
        ObjectKind::Bush,
    )?;
    append_kind(
        &mut objects,
        &mut cursor,
        &mut next_id,
        ceil_div(
            ELIGIBLE_LAND_AREA_M2 * u32::from(config.objects.boulders_per_hectare),
            10_000,
        ),
        ObjectKind::Boulder,
    )?;
    append_kind(
        &mut objects,
        &mut cursor,
        &mut next_id,
        ceil_div(
            ELIGIBLE_LAND_AREA_M2 * u32::from(config.objects.stumps_per_hectare),
            10_000,
        ),
        ObjectKind::Stump,
    )?;
    append_kind(
        &mut objects,
        &mut cursor,
        &mut next_id,
        ceil_div(
            ELIGIBLE_LAND_AREA_M2 * u32::from(config.objects.rocks_per_hectare),
            10_000,
        ),
        ObjectKind::Rock,
    )?;

    let ruin = ruin();
    let manifest = CuratedManifest {
        seed: config.seed,
        parameters_digest: parameters_digest_from_bytes(region_config_bytes, ruin_stamp_bytes),
        generated_by: "moria-curate generate".to_owned(),
        features: features(config.seed),
        water_bodies: water_bodies(config.seed),
        objects,
        ruin,
        route: route(),
    };
    validate_manifest(&manifest, &stamp, &config)?;
    Ok(manifest)
}

/// Serializes a generated manifest using the only checked-in representation.
pub fn canonical_manifest_ron(manifest: &CuratedManifest) -> Result<String, CurationGenerateError> {
    manifest.validate().map_err(manifest_error)?;
    let options = ron::ser::PrettyConfig::new()
        .depth_limit(4)
        .separate_tuple_members(true)
        .enumerate_arrays(true);
    let body = ron::ser::to_string_pretty(manifest, options)
        .map_err(|error| CurationGenerateError::Contract(error.to_string()))?;
    Ok(format!("{GENERATED_FILE_COMMENT}{body}\n"))
}

fn validate_manifest(
    manifest: &CuratedManifest,
    stamp: &SparseVoxelStamp,
    config: &RegionConfig,
) -> Result<(), CurationGenerateError> {
    manifest.validate().map_err(manifest_error)?;
    let index = build_object_index(&manifest.objects, &ObjectIndexConfig::default())
        .map_err(manifest_error)?;
    validate_object_shape_disjointness(&index, &manifest.ruin, stamp).map_err(manifest_error)?;
    validate_forest_contract(manifest, config)
}

fn manifest_error(error: ManifestError) -> CurationGenerateError {
    CurationGenerateError::Contract(error.to_string())
}

fn append_kind(
    objects: &mut Vec<ObjectPlacement>,
    cursor: &mut CandidateCursor,
    next_id: &mut u64,
    count: u32,
    kind: ObjectKind,
) -> Result<(), CurationGenerateError> {
    for _ in 0..count {
        objects.push(placement(*next_id, cursor.next()?, kind));
        *next_id += 1;
    }
    Ok(())
}

fn tree(id: u64, point: WorldPointQ8, birch: bool, canopy: u16) -> ObjectPlacement {
    ObjectPlacement {
        kind: if birch {
            ObjectKind::TreeA
        } else {
            ObjectKind::TreeB
        },
        species: Some(SpeciesId(if birch { 1 } else { 2 })),
        shape: VoxelObjectShape::Tree {
            trunk_radius_q8: if birch { 70 } else { 90 },
            trunk_height_q8: if birch { 2_560 } else { 3_584 },
            canopy_radii_q8: [canopy, canopy, canopy],
        },
        ..placement_at(id, point)
    }
}

const fn canopy_radius(index: u32, birch_count: u32) -> u16 {
    let species_index = if index < birch_count {
        index
    } else {
        index - birch_count
    };
    if species_index < 16 {
        512
    } else if species_index < 32 {
        896
    } else {
        768
    }
}

fn features(seed: u64) -> Vec<FeatureInstance> {
    let bounds =
        |min, max| AabbQ8::new(min, max).expect("fixed Product One feature bounds are valid");
    vec![
        FeatureInstance {
            id: 1,
            kind: FeatureKind::Stratum,
            bounds: bounds(
                WorldPointQ8::new(-128_000, -32_768, -128_000),
                WorldPointQ8::new(128_000, 32_768, 128_000),
            ),
            host_material: CUT_STONE,
            depth_q8: 0,
            orientation_q16: [0, 0, 0, 65_536],
            generator_key: seed,
        },
        FeatureInstance {
            id: 2,
            kind: FeatureKind::KarstCave,
            bounds: bounds(
                WorldPointQ8::new(-8_192, -12_288, -2_048),
                WorldPointQ8::new(8_192, 2_048, 2_048),
            ),
            host_material: CUT_STONE,
            depth_q8: 0,
            orientation_q16: [0, 0, 0, 65_536],
            generator_key: seed,
        },
        FeatureInstance {
            id: 3,
            kind: FeatureKind::Aquifer,
            bounds: bounds(
                WorldPointQ8::new(-4_096, -10_240, -1_024),
                WorldPointQ8::new(4_096, -8_704, 1_024),
            ),
            host_material: WATER,
            depth_q8: 0,
            orientation_q16: [0, 0, 0, 65_536],
            generator_key: seed,
        },
        FeatureInstance {
            id: 4,
            kind: FeatureKind::IronVein,
            bounds: bounds(
                WorldPointQ8::new(-1_024, -9_728, -4_096),
                WorldPointQ8::new(1_024, -8_192, 4_096),
            ),
            host_material: IRON_ORE,
            depth_q8: 0,
            orientation_q16: [0, 0, 0, 65_536],
            generator_key: seed,
        },
        FeatureInstance {
            id: 5,
            kind: FeatureKind::Topsoil,
            bounds: bounds(
                WorldPointQ8::new(-128_000, 15_872, -128_000),
                WorldPointQ8::new(128_000, 16_128, 128_000),
            ),
            host_material: CUT_STONE,
            depth_q8: 0,
            orientation_q16: [0, 0, 0, 65_536],
            generator_key: seed,
        },
        FeatureInstance {
            id: 6,
            kind: FeatureKind::Subsoil,
            bounds: bounds(
                WorldPointQ8::new(-128_000, 15_104, -128_000),
                WorldPointQ8::new(128_000, 15_872, 128_000),
            ),
            host_material: GRANITE,
            depth_q8: 0,
            orientation_q16: [0, 0, 0, 65_536],
            generator_key: seed,
        },
    ]
}

fn water_bodies(seed: u64) -> Vec<WaterBodyDef> {
    vec![
        WaterBodyDef {
            id: 1,
            kind: WaterKind::River,
            surface_y_q8: SURFACE_Y_METERS * 256,
            footprint: vec![
                WorldPointQ8::new(-128_000, SURFACE_Y_METERS * 256, -1_280),
                WorldPointQ8::new(128_000, SURFACE_Y_METERS * 256, -1_280),
                WorldPointQ8::new(128_000, SURFACE_Y_METERS * 256, 1_280),
                WorldPointQ8::new(-128_000, SURFACE_Y_METERS * 256, 1_280),
            ],
            bed_profile_key: seed,
        },
        WaterBodyDef {
            id: 2,
            kind: WaterKind::Lake,
            surface_y_q8: SURFACE_Y_METERS * 256,
            footprint: vec![
                WorldPointQ8::new(-25_600, SURFACE_Y_METERS * 256, -25_600),
                WorldPointQ8::new(-20_480, SURFACE_Y_METERS * 256, -25_600),
                WorldPointQ8::new(-20_480, SURFACE_Y_METERS * 256, -20_480),
                WorldPointQ8::new(-25_600, SURFACE_Y_METERS * 256, -20_480),
            ],
            bed_profile_key: seed,
        },
    ]
}

fn route() -> Vec<RouteWaypoint> {
    let tags = [
        RouteTag::Meadow,
        RouteTag::Forest,
        RouteTag::River,
        RouteTag::Lake,
        RouteTag::CliffTop,
        RouteTag::RockShelves,
        RouteTag::RuinStairBottom,
        RouteTag::RuinStairTop,
        RouteTag::CaveMouth,
        RouteTag::Aquifer,
        RouteTag::OreVein,
        RouteTag::CaveFloor,
        RouteTag::SignatureCarveHillside,
    ];
    tags.into_iter()
        .enumerate()
        .map(|(order, tag)| RouteWaypoint {
            order: order as u8,
            point: WorldPointQ8::new(
                -12_800 + order as i32 * 2_048,
                SURFACE_Y_METERS * 256
                    - if matches!(
                        tag,
                        RouteTag::Aquifer | RouteTag::OreVein | RouteTag::CaveFloor
                    ) {
                        10_240
                    } else {
                        0
                    },
                12_800,
            ),
            tags: vec![tag],
        })
        .collect()
}

fn validate_forest_contract(
    manifest: &CuratedManifest,
    config: &RegionConfig,
) -> Result<(), CurationGenerateError> {
    let required_features = [
        FeatureKind::Stratum,
        FeatureKind::KarstCave,
        FeatureKind::Aquifer,
        FeatureKind::IronVein,
    ];
    if required_features.iter().any(|kind| {
        !manifest
            .features
            .iter()
            .any(|feature| feature.kind == *kind)
    }) || !manifest
        .water_bodies
        .iter()
        .any(|body| body.kind == WaterKind::River)
        || !manifest
            .water_bodies
            .iter()
            .any(|body| body.kind == WaterKind::Lake)
    {
        return Err(CurationGenerateError::Contract(
            "complete route geology and water features are required".to_owned(),
        ));
    }
    let required_tags = [
        RouteTag::Forest,
        RouteTag::CaveMouth,
        RouteTag::Aquifer,
        RouteTag::OreVein,
        RouteTag::CaveFloor,
    ];
    if required_tags.iter().any(|tag| {
        !manifest
            .route
            .iter()
            .any(|waypoint| waypoint.tags.contains(tag))
    }) {
        return Err(CurationGenerateError::Contract(
            "complete route tags are required".to_owned(),
        ));
    }
    for species in [SpeciesId(1), SpeciesId(2)] {
        let trees = manifest
            .objects
            .iter()
            .filter(|object| object.species == Some(species))
            .collect::<Vec<_>>();
        let lower = trees
            .iter()
            .filter(|tree| canopy_horizontal_radius(tree) <= 640)
            .count();
        let upper = trees
            .iter()
            .filter(|tree| canopy_horizontal_radius(tree) >= 896)
            .count();
        if lower < 16 || upper < 16 {
            return Err(CurationGenerateError::Contract(
                "each tree species needs sixteen lower and upper canopy placements".to_owned(),
            ));
        }
    }
    let minimum_trees = ceil_div(FOREST_AREA_M2, 25);
    let tree_count = manifest
        .objects
        .iter()
        .filter(|object| matches!(object.kind, ObjectKind::TreeA | ObjectKind::TreeB))
        .count() as u32;
    if tree_count < minimum_trees || config.biome.forest_tree_spacing_m > TREE_SPACING_METERS as u8
    {
        return Err(CurationGenerateError::Contract(
            "forest area, density, or spacing contract failed".to_owned(),
        ));
    }
    Ok(())
}

fn canopy_horizontal_radius(tree: &&ObjectPlacement) -> u16 {
    match tree.shape {
        VoxelObjectShape::Tree {
            canopy_radii_q8, ..
        } => canopy_radii_q8[0].max(canopy_radii_q8[2]),
        _ => 0,
    }
}

fn placement(id: u64, point: WorldPointQ8, kind: ObjectKind) -> ObjectPlacement {
    let shape = match kind {
        ObjectKind::Bush => VoxelObjectShape::Bush {
            radii_q8: [256, 192, 256],
        },
        ObjectKind::Boulder => VoxelObjectShape::Boulder {
            radii_q8: [384, 384, 384],
            perturbation_key: id,
        },
        ObjectKind::Stump => VoxelObjectShape::Stump {
            radius_q8: 96,
            height_q8: 128,
        },
        ObjectKind::Rock => VoxelObjectShape::Rock {
            radii_q8: [128, 96, 128],
            perturbation_key: id,
        },
        ObjectKind::TreeA | ObjectKind::TreeB | ObjectKind::Ruin => {
            unreachable!("handled separately")
        }
    };
    ObjectPlacement {
        kind,
        species: None,
        shape,
        ..placement_at(id, point)
    }
}

fn placement_at(id: u64, point: WorldPointQ8) -> ObjectPlacement {
    ObjectPlacement {
        id: ObjectId(id),
        kind: ObjectKind::Bush,
        transform_q: QuantizedTransform {
            translation: point,
            yaw_quarter_turns: 0,
            uniform_scale_q8: 256,
        },
        species: None,
        shape: VoxelObjectShape::Bush {
            radii_q8: [1, 1, 1],
        },
        anchor: VoxelCoord::new(point.x / 64, point.y / 64, point.z / 64),
    }
}

fn ruin() -> RuinPoi {
    let point = WorldPointQ8::new(0, SURFACE_Y_METERS * 256, 0);
    RuinPoi {
        placement: ObjectPlacement {
            id: ObjectId(0),
            kind: ObjectKind::Ruin,
            transform_q: QuantizedTransform {
                translation: point,
                yaw_quarter_turns: 0,
                uniform_scale_q8: 256,
            },
            species: None,
            shape: VoxelObjectShape::SparseStamp {
                asset_key: "moria.stamps.ruin_p1".to_owned(),
            },
            anchor: VoxelCoord::new(0, SURFACE_Y_METERS * 4, 0),
        },
        stair_bottom: point,
        stair_top: WorldPointQ8::new(0, (SURFACE_Y_METERS + 3) * 256, 512),
    }
}

fn ceil_div(value: u32, divisor: u32) -> u32 {
    value.div_ceil(divisor)
}

struct CandidateCursor {
    x: i32,
    z: i32,
}

impl CandidateCursor {
    const fn new() -> Self {
        Self { x: -490, z: -490 }
    }

    fn next(&mut self) -> Result<WorldPointQ8, CurationGenerateError> {
        loop {
            if self.z > 490 {
                return Err(CurationGenerateError::Contract(
                    "candidate grid cannot satisfy required placement counts".to_owned(),
                ));
            }
            let point = WorldPointQ8::new(self.x * 256, SURFACE_Y_METERS * 256, self.z * 256);
            self.x += TREE_SPACING_METERS;
            if self.x > 490 {
                self.x = -490;
                self.z += TREE_SPACING_METERS;
            }
            if point.x.abs() >= 2_560 || point.z.abs() >= 2_560 {
                return Ok(point);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::{FeatureKind, RouteTag, SpeciesId, VoxelObjectShape, WaterKind};

    use super::{canonical_manifest_ron, generate_manifest};

    #[test]
    fn generation_is_byte_deterministic_and_uses_both_input_byte_streams() {
        let region = include_bytes!("../../../../assets/config/product_one_region.ron");
        let stamp = include_bytes!("../../../../assets/stamps/ruin_p1.ron");
        let first = generate_manifest(region, stamp).unwrap();
        let second = generate_manifest(region, stamp).unwrap();

        assert_eq!(first, second);
        assert_eq!(
            canonical_manifest_ron(&first).unwrap(),
            canonical_manifest_ron(&second).unwrap()
        );
        assert!(!first.objects.is_empty());
    }

    #[test]
    fn generation_covers_the_complete_route_and_canopy_contract() {
        let manifest = generate_manifest(
            include_bytes!("../../../../assets/config/product_one_region.ron"),
            include_bytes!("../../../../assets/stamps/ruin_p1.ron"),
        )
        .unwrap();

        for kind in [
            FeatureKind::Stratum,
            FeatureKind::KarstCave,
            FeatureKind::Aquifer,
            FeatureKind::IronVein,
        ] {
            assert!(manifest.features.iter().any(|feature| feature.kind == kind));
        }
        assert!(
            manifest
                .water_bodies
                .iter()
                .any(|body| body.kind == WaterKind::River)
        );
        assert!(
            manifest
                .water_bodies
                .iter()
                .any(|body| body.kind == WaterKind::Lake)
        );
        for tag in [
            RouteTag::Forest,
            RouteTag::CaveMouth,
            RouteTag::Aquifer,
            RouteTag::OreVein,
            RouteTag::CaveFloor,
        ] {
            assert!(
                manifest
                    .route
                    .iter()
                    .any(|waypoint| waypoint.tags.contains(&tag))
            );
        }
        for species in [SpeciesId(1), SpeciesId(2)] {
            let radii = manifest
                .objects
                .iter()
                .filter(|object| object.species == Some(species))
                .filter_map(|object| match object.shape {
                    VoxelObjectShape::Tree {
                        canopy_radii_q8, ..
                    } => Some(canopy_radii_q8[0].max(canopy_radii_q8[2])),
                    _ => None,
                })
                .collect::<Vec<_>>();
            assert!(radii.iter().filter(|&&radius| radius <= 640).count() >= 16);
            assert!(radii.iter().filter(|&&radius| radius >= 896).count() >= 16);
        }
    }
}
