use std::{fs, path::PathBuf};

use moria_world::{
    CuratedManifest, parameters_digest_from_bytes,
    presentation::{AssetId, AssetLoader, AssetMissingAction, RuntimeAssetProfile},
};

const CURATED_MANIFEST_PATH: &str = "config/curated_manifest.ron";
const REGION_CONFIG_PATH: &str = "config/product_one_region.ron";
const RUIN_STAMP_PATH: &str = "stamps/ruin_p1.ron";
const GENERATED_FILE_COMMENT: &str = "// Generated by moria-curate generate; DO NOT EDIT.\n";

#[test]
fn curated_manifest_placeholder_uses_its_immutable_runtime_declaration_and_digest_sources() {
    let loader = AssetLoader::new();
    let declaration = loader.declaration(AssetId::CuratedManifest);

    assert_eq!(declaration.id.stable_id(), "moria.config.curated_manifest");
    assert_eq!(declaration.path, CURATED_MANIFEST_PATH);
    assert_eq!(
        loader.resolve_runtime_path(CURATED_MANIFEST_PATH),
        Ok(declaration)
    );
    assert_eq!(
        loader.validation_fixture(AssetId::CuratedManifest).key,
        declaration.id.stable_id()
    );
    assert_eq!(
        loader.missing_asset_action(AssetId::CuratedManifest, RuntimeAssetProfile::Development),
        AssetMissingAction::Fatal,
        "the generated authoritative manifest cannot use a development fallback"
    );
    assert_eq!(
        loader.missing_asset_action(AssetId::CuratedManifest, RuntimeAssetProfile::Release),
        AssetMissingAction::Fatal
    );

    let source = fs::read_to_string(asset_path(CURATED_MANIFEST_PATH))
        .expect("curated manifest placeholder exists at its declared runtime path");
    assert!(source.starts_with(GENERATED_FILE_COMMENT));
    let manifest: CuratedManifest = ron::de::from_str(&source)
        .expect("curated manifest placeholder uses the generated RON schema");

    assert_eq!(manifest.seed, 0x4D4F_5249_415F_5031);
    assert_eq!(manifest.generated_by, "moria-curate generate");
    assert!(manifest.objects.len() >= 4_800);
    assert!(is_sorted_by_key(&manifest.features, |feature| feature.id));
    assert!(is_sorted_by_key(&manifest.water_bodies, |water| water.id));
    assert!(is_sorted_by_key(&manifest.objects, |object| object.id));
    assert!(is_sorted_by_key(&manifest.route, |waypoint| waypoint.order));
    assert_eq!(manifest.ruin.placement.id, moria_world::ObjectId(0));
    manifest
        .validate()
        .expect("curated manifest placeholder satisfies the public metadata contract");

    let region_bytes = fs::read(asset_path(REGION_CONFIG_PATH))
        .expect("the manifest digest reads the predeclared region configuration path");
    let ruin_bytes = fs::read(asset_path(RUIN_STAMP_PATH))
        .expect("the manifest digest reads the predeclared ruin stamp path");
    assert!(manifest_matches_inputs(
        &manifest,
        &region_bytes,
        &ruin_bytes
    ));

    let mut changed_region = region_bytes.clone();
    changed_region.push(b' ');
    assert!(!manifest_matches_inputs(
        &manifest,
        &changed_region,
        &ruin_bytes
    ));

    let mut changed_ruin = ruin_bytes.clone();
    changed_ruin.push(b' ');
    assert!(!manifest_matches_inputs(
        &manifest,
        &region_bytes,
        &changed_ruin
    ));
}

fn is_sorted_by_key<T, K: Ord>(values: &[T], key: impl Fn(&T) -> K) -> bool {
    values.windows(2).all(|pair| key(&pair[0]) < key(&pair[1]))
}

fn manifest_matches_inputs(
    manifest: &CuratedManifest,
    region_bytes: &[u8],
    ruin_bytes: &[u8],
) -> bool {
    manifest.parameters_digest == parameters_digest_from_bytes(region_bytes, ruin_bytes)
}

fn asset_path(path: &str) -> PathBuf {
    let declaration = AssetLoader::new()
        .resolve_runtime_path(path)
        .expect("all manifest inputs use immutable shared loader routes");
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .join("assets")
        .join(declaration.path)
}
