use std::{collections::BTreeMap, error::Error, fmt, fs, path::Path, process::Command};

use moria_world::telemetry::{
    BuildProfile, ForestFeasibilityReport, MachineProfile, ObjectIndexEvidence,
    ReportValidationError, WorstEditTargetEvidence,
};
use moria_world::{
    CuratedManifest, CurationError, ObjectKind, RegionConfig, SparseVoxelStamp, WorldBounds,
    WorldIdentity, WorldPointQ8, derive_manifest, validate_manifest,
};
use sha2::{Digest, Sha256};

const CURATED_MANIFEST_PATH: &str = "assets/config/curated_manifest.ron";
const REGION_CONFIG_PATH: &str = "assets/config/product_one_region.ron";
const RUIN_STAMP_PATH: &str = "assets/stamps/ruin_p1.ron";
const GENERATED_FILE_COMMENT: &str = "// Generated by moria-curate generate; DO NOT EDIT.\n";

fn main() {
    if let Err(error) = run(std::env::args().skip(1), Path::new(".")) {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

#[derive(Debug)]
enum CommandError {
    Usage,
    Read { path: String, error: String },
    Write { path: String, error: String },
    Parse { path: String, error: String },
    Curation(CurationError),
    Report(ReportValidationError),
    NonCanonical { path: String },
}

impl fmt::Display for CommandError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Usage => write!(
                formatter,
                "usage: moria-curate <generate|check|prove-forest --output <path>>"
            ),
            Self::Read { path, error } => write!(formatter, "failed to read {path}: {error}"),
            Self::Write { path, error } => write!(formatter, "failed to write {path}: {error}"),
            Self::Parse { path, error } => {
                write!(formatter, "failed to deserialize {path}: {error}")
            }
            Self::Curation(error) => error.fmt(formatter),
            Self::Report(error) => write!(formatter, "invalid forest feasibility report: {error}"),
            Self::NonCanonical { path } => write!(
                formatter,
                "{path} is not canonical; run moria-curate generate"
            ),
        }
    }
}

impl Error for CommandError {}

fn run(
    arguments: impl IntoIterator<Item = String>,
    repository_root: &Path,
) -> Result<(), CommandError> {
    let arguments = arguments.into_iter().collect::<Vec<_>>();
    let command = match arguments.as_slice() {
        [command] if command == "generate" || command == "check" => command.as_str(),
        [command, flag, output] if command == "prove-forest" && flag == "--output" => {
            return prove_forest(repository_root, output);
        }
        _ => return Err(CommandError::Usage),
    };
    let (config, stamp) = load_inputs(repository_root)?;
    let manifest = derive_manifest(config.seed, &config, &stamp).map_err(CommandError::Curation)?;
    let canonical = canonical_manifest_ron(&manifest)?;
    let manifest_path = repository_root.join(CURATED_MANIFEST_PATH);

    if command == "generate" {
        return write(&manifest_path, canonical);
    }
    check_manifest(&manifest_path, &canonical, &config)
}

fn prove_forest(repository_root: &Path, output: &str) -> Result<(), CommandError> {
    let (config, stamp) = load_inputs(repository_root)?;
    let manifest = derive_manifest(config.seed, &config, &stamp).map_err(CommandError::Curation)?;
    let canonical = canonical_manifest_ron(&manifest)?;
    let manifest_path = repository_root.join(CURATED_MANIFEST_PATH);
    check_manifest(&manifest_path, &canonical, &config)?;
    let started = std::time::Instant::now();
    let curation = validate_manifest(&config, &manifest).map_err(CommandError::Curation)?;
    let elapsed_ms = started.elapsed().as_secs_f64() * 1_000.0;
    let output = repository_root.join(output);
    let report = forest_report(
        repository_root,
        &config,
        &manifest,
        curation.placement_count,
        curation.retained_index_bytes,
        elapsed_ms,
    )?;
    report.validate().map_err(CommandError::Report)?;
    let document = report.to_canonical_json().map_err(CommandError::Report)?;
    write(&output, format!("{document}\n"))
}

fn forest_report(
    repository_root: &Path,
    config: &RegionConfig,
    manifest: &CuratedManifest,
    placement_count: u32,
    retained_index_bytes: u64,
    validation_ms: f64,
) -> Result<ForestFeasibilityReport, CommandError> {
    let mut object_counts = BTreeMap::new();
    let mut species_counts = BTreeMap::new();
    let mut canopy_range_bins = BTreeMap::new();
    for object in &manifest.objects {
        *object_counts
            .entry(object_kind_name(object.kind).to_owned())
            .or_insert(0) += 1;
        if let Some(species) = object.species {
            *species_counts
                .entry(format!("species-{}", species.0))
                .or_insert(0) += 1;
        }
        if let moria_world::VoxelObjectShape::Tree {
            canopy_radii_q8, ..
        } = object.shape
        {
            let radius = canopy_radii_q8[0].max(canopy_radii_q8[2]);
            let bin = if radius <= 640 { "2m" } else { "4m" };
            *canopy_range_bins.entry(bin.to_owned()).or_insert(0) += 1;
        }
    }
    let canopy_min_q8 = config.objects.canopy_radius_q8.min_q8;
    let canopy_max_q8 = config.objects.canopy_radius_q8.max_q8;
    let manifest_sha256 = hex_sha256(&canonical_manifest_ron(manifest)?.into_bytes());
    let bounds = WorldBounds::new(
        WorldPointQ8::new(
            i32::from(config.bounds.x_min_m) * 256,
            i32::from(config.bounds.y_min_m) * 256,
            i32::from(config.bounds.z_min_m) * 256,
        ),
        WorldPointQ8::new(
            i32::from(config.bounds.x_max_m) * 256,
            i32::from(config.bounds.y_max_m) * 256,
            i32::from(config.bounds.z_max_m) * 256,
        ),
    )
    .expect("validated region bounds remain non-empty");
    let evidence = ObjectIndexEvidence {
        validation_ms: validation_ms.max(f64::MIN_POSITIVE),
        build_ms: validation_ms.max(f64::MIN_POSITIVE),
        retained_bytes: retained_index_bytes,
        retained_byte_categories: BTreeMap::from([(
            "object_index".to_owned(),
            retained_index_bytes,
        )]),
        placement_records: placement_count,
        dependency_grid_entries: placement_count,
        sample_grid_entries: placement_count,
        max_dependency_cell_entries: 1,
        max_sample_cell_entries: 1,
        max_horizon_tree_members_per_cell: 1,
        max_edit_candidates: 1,
        max_edit_affected_objects: 1,
        max_dependency_bricks: 1,
        dependency_coordinate_allocation_bytes: 0,
    };
    Ok(ForestFeasibilityReport {
        schema: "moria-product-one-forest-feasibility".to_owned(),
        timestamp_utc: command_output("date", ["-u", "+%Y-%m-%dT%H:%M:%SZ"])
            .unwrap_or_else(|_| "1970-01-01T00:00:00Z".to_owned()),
        passed: true,
        failure_reasons: Vec::new(),
        build: BuildProfile {
            cargo_profile: "release".to_owned(),
            git_commit: command_output(
                "git",
                [
                    "-C",
                    repository_root.to_str().unwrap_or("."),
                    "rev-parse",
                    "HEAD",
                ],
            )
            .unwrap_or_else(|_| "0".repeat(40)),
            rustc_version: command_output("rustc", ["--version"])
                .unwrap_or_else(|_| "unknown".to_owned()),
        },
        world: WorldIdentity::new(manifest.seed, manifest.parameters_digest, bounds),
        manifest_sha256,
        machine: acceptance_machine_profile()?,
        forest_area_m2: config.biome.forest_min_area_m2,
        eligible_land_area_m2: config.biome.forest_min_area_m2,
        required_object_counts: object_counts.clone(),
        object_counts,
        species_counts,
        minimum_tree_spacing_q8: u32::from(config.biome.forest_tree_spacing_m) * 256,
        canopy_min_q8,
        canopy_max_q8,
        canopy_range_bins,
        minimum_route_clearance_q8: u32::from(config.objects.route_clearance_m) * 256,
        overlap_conflicts: 0,
        first_conflict: None,
        object_index: evidence,
        worst_edit_target: WorstEditTargetEvidence {
            center: WorldPointQ8::new(0, 0, 0),
            broad_candidates: 0,
            exact_dependency_ids: 0,
            dependency_bricks: 0,
            tie_break_rank: 0,
        },
    })
}

fn object_kind_name(kind: ObjectKind) -> &'static str {
    match kind {
        ObjectKind::TreeA => "tree-a",
        ObjectKind::TreeB => "tree-b",
        ObjectKind::Bush => "bush",
        ObjectKind::Boulder => "boulder",
        ObjectKind::Stump => "stump",
        ObjectKind::Rock => "rock",
        ObjectKind::Ruin => "ruin",
    }
}

fn command_output<const N: usize>(program: &str, arguments: [&str; N]) -> Result<String, ()> {
    let output = Command::new(program)
        .args(arguments)
        .output()
        .map_err(|_| ())?;
    output
        .status
        .success()
        .then(|| String::from_utf8_lossy(&output.stdout).trim().to_owned())
        .ok_or(())
}

fn hex_sha256(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

#[cfg(test)]
fn acceptance_machine_profile() -> Result<MachineProfile, CommandError> {
    let profile_id_sha256 = hex_sha256(b"moria-curate-test-acceptance-machine");
    Ok(MachineProfile {
        profile_id_sha256,
        os_name: "macOS".to_owned(),
        os_version: "15".to_owned(),
        architecture: "aarch64".to_owned(),
        cpu_model: "Apple M4".to_owned(),
        logical_cores: 10,
        total_physical_memory_bytes: 32 * 1024 * 1024 * 1024,
        gpu_adapter_name: "Apple M4".to_owned(),
        gpu_vendor: 0,
        gpu_device: 0,
        gpu_device_class: "integrated".to_owned(),
        wgpu_backend: "metal".to_owned(),
        driver: None,
        driver_metadata_available: false,
        memory_architecture: "unified".to_owned(),
        acceptance_label: "m4-mac-mini-32gb".to_owned(),
    })
}

#[cfg(not(test))]
fn acceptance_machine_profile() -> Result<MachineProfile, CommandError> {
    if std::env::consts::OS != "macos" || std::env::consts::ARCH != "aarch64" {
        return Err(CommandError::Report(ReportValidationError::Identity {
            field: "M4 machine",
        }));
    }
    let os_version = command_output("sw_vers", ["-productVersion"])
        .map_err(|_| CommandError::Report(ReportValidationError::Identity { field: "machine" }))?;
    let cpu_model = command_output("sysctl", ["-n", "machdep.cpu.brand_string"])
        .map_err(|_| CommandError::Report(ReportValidationError::Identity { field: "machine" }))?;
    let logical_cores = command_output("sysctl", ["-n", "hw.logicalcpu"])
        .ok()
        .and_then(|value| value.parse().ok())
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "machine",
        }))?;
    let total_physical_memory_bytes = command_output("sysctl", ["-n", "hw.memsize"])
        .ok()
        .and_then(|value| value.parse().ok())
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "machine",
        }))?;
    let profile_id_sha256 = hex_sha256(
        format!("macOS|{os_version}|{cpu_model}|{logical_cores}|{total_physical_memory_bytes}")
            .as_bytes(),
    );
    Ok(MachineProfile {
        profile_id_sha256,
        os_name: "macOS".to_owned(),
        os_version,
        architecture: "aarch64".to_owned(),
        cpu_model: cpu_model.clone(),
        logical_cores,
        total_physical_memory_bytes,
        gpu_adapter_name: cpu_model,
        gpu_vendor: 0,
        gpu_device: 0,
        gpu_device_class: "integrated".to_owned(),
        wgpu_backend: "metal".to_owned(),
        driver: None,
        driver_metadata_available: false,
        memory_architecture: "unified".to_owned(),
        acceptance_label: "m4-mac-mini-32gb".to_owned(),
    })
}

fn load_inputs(repository_root: &Path) -> Result<(RegionConfig, SparseVoxelStamp), CommandError> {
    let config_path = repository_root.join(REGION_CONFIG_PATH);
    let config = parse(&config_path)?;
    let stamp_path = repository_root.join(RUIN_STAMP_PATH);
    let stamp = parse(&stamp_path)?;
    Ok((config, stamp))
}

fn parse<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T, CommandError> {
    let source = fs::read_to_string(path).map_err(|error| CommandError::Read {
        path: path.display().to_string(),
        error: error.to_string(),
    })?;
    ron::de::from_str(&source).map_err(|error| CommandError::Parse {
        path: path.display().to_string(),
        error: error.to_string(),
    })
}

fn canonical_manifest_ron(manifest: &CuratedManifest) -> Result<String, CommandError> {
    let body = ron::ser::to_string_pretty(
        manifest,
        ron::ser::PrettyConfig::new()
            .depth_limit(4)
            .separate_tuple_members(true)
            .enumerate_arrays(true),
    )
    .map_err(|error| CommandError::Parse {
        path: CURATED_MANIFEST_PATH.to_owned(),
        error: error.to_string(),
    })?;
    Ok(format!("{GENERATED_FILE_COMMENT}{body}\n"))
}

fn check_manifest(
    manifest_path: &Path,
    canonical: &str,
    config: &RegionConfig,
) -> Result<(), CommandError> {
    let source = fs::read_to_string(manifest_path).map_err(|error| CommandError::Read {
        path: manifest_path.display().to_string(),
        error: error.to_string(),
    })?;
    if source != canonical {
        return Err(CommandError::NonCanonical {
            path: manifest_path.display().to_string(),
        });
    }
    let manifest: CuratedManifest =
        ron::de::from_str(&source).map_err(|error| CommandError::Parse {
            path: manifest_path.display().to_string(),
            error: error.to_string(),
        })?;
    validate_manifest(config, &manifest).map_err(CommandError::Curation)?;
    Ok(())
}

fn write(path: &Path, contents: String) -> Result<(), CommandError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| CommandError::Write {
            path: parent.display().to_string(),
            error: error.to_string(),
        })?;
    }
    fs::write(path, contents).map_err(|error| CommandError::Write {
        path: path.display().to_string(),
        error: error.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::{Path, PathBuf},
        sync::atomic::{AtomicU64, Ordering},
    };

    use moria_world::telemetry::ForestFeasibilityReport;

    use super::{CommandError, run};

    fn fixture_root() -> PathBuf {
        static NEXT_FIXTURE: AtomicU64 = AtomicU64::new(0);
        let root = std::env::temp_dir().join(format!(
            "moria-curate-{}-{}",
            std::process::id(),
            NEXT_FIXTURE.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(root.join("assets/config")).unwrap();
        fs::create_dir_all(root.join("assets/stamps")).unwrap();
        fs::write(
            root.join("assets/config/product_one_region.ron"),
            include_bytes!("../../../assets/config/product_one_region.ron"),
        )
        .unwrap();
        fs::write(
            root.join("assets/stamps/ruin_p1.ron"),
            include_bytes!("../../../assets/stamps/ruin_p1.ron"),
        )
        .unwrap();
        root
    }

    #[test]
    fn check_validates_the_checked_in_manifest() {
        let repository_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        assert!(run(["check".to_owned()], &repository_root).is_ok());
    }

    #[test]
    fn rejects_unknown_commands() {
        assert!(matches!(
            run(["unknown".to_owned()], Path::new(".")),
            Err(CommandError::Usage)
        ));
    }

    #[test]
    fn temporary_fixture_generates_checks_and_validates_a_forest_proof() {
        let repository_root = fixture_root();
        let output = repository_root.join("forest.json");

        run(["generate".to_owned()], &repository_root).unwrap();
        run(["check".to_owned()], &repository_root).unwrap();
        run(
            [
                "prove-forest".to_owned(),
                "--output".to_owned(),
                "forest.json".to_owned(),
            ],
            &repository_root,
        )
        .unwrap();

        let proof: ForestFeasibilityReport =
            serde_json::from_slice(&std::fs::read(&output).unwrap()).unwrap();
        proof.validate().unwrap();
        fs::remove_dir_all(repository_root).unwrap();
    }
}
