use std::{error::Error, fmt, fs, path::Path};

use moria_world::{
    CuratedManifest, CurationError, CurationReport, RegionConfig, derive_manifest_from_bytes,
    validate_manifest,
};

const CURATED_MANIFEST_PATH: &str = "assets/config/curated_manifest.ron";
const REGION_CONFIG_PATH: &str = "assets/config/product_one_region.ron";
const RUIN_STAMP_PATH: &str = "assets/stamps/ruin_p1.ron";
const GENERATED_FILE_COMMENT: &str = "// Generated by moria-curate generate; DO NOT EDIT.\n";

fn main() {
    if let Err(error) = run(std::env::args().skip(1), Path::new(".")) {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

#[derive(Debug)]
enum CommandError {
    Usage,
    Read { path: String, error: String },
    Write { path: String, error: String },
    Parse { path: String, error: String },
    Curation(CurationError),
    NonCanonical { path: String },
}

impl fmt::Display for CommandError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Usage => write!(
                formatter,
                "usage: moria-curate <generate|check|prove-forest --output <path>>"
            ),
            Self::Read { path, error } => write!(formatter, "failed to read {path}: {error}"),
            Self::Write { path, error } => write!(formatter, "failed to write {path}: {error}"),
            Self::Parse { path, error } => {
                write!(formatter, "failed to deserialize {path}: {error}")
            }
            Self::Curation(error) => error.fmt(formatter),
            Self::NonCanonical { path } => write!(
                formatter,
                "{path} is not canonical; run moria-curate generate"
            ),
        }
    }
}

impl Error for CommandError {}

fn run(
    arguments: impl IntoIterator<Item = String>,
    repository_root: &Path,
) -> Result<(), CommandError> {
    let arguments = arguments.into_iter().collect::<Vec<_>>();
    let command = match arguments.as_slice() {
        [command] if command == "generate" || command == "check" => command.as_str(),
        [command, flag, output] if command == "prove-forest" && flag == "--output" => {
            return prove_forest(repository_root, output);
        }
        _ => return Err(CommandError::Usage),
    };
    let (config_bytes, stamp_bytes, config) = load_inputs(repository_root)?;
    let manifest =
        derive_manifest_from_bytes(&config_bytes, &stamp_bytes).map_err(CommandError::Curation)?;
    let canonical = canonical_manifest_ron(&manifest)?;
    let manifest_path = repository_root.join(CURATED_MANIFEST_PATH);

    if command == "generate" {
        return write(&manifest_path, canonical);
    }
    check_manifest(&manifest_path, &canonical, &config)
}

fn prove_forest(repository_root: &Path, output: &str) -> Result<(), CommandError> {
    let (config_bytes, stamp_bytes, config) = load_inputs(repository_root)?;
    let manifest =
        derive_manifest_from_bytes(&config_bytes, &stamp_bytes).map_err(CommandError::Curation)?;
    let canonical = canonical_manifest_ron(&manifest)?;
    let manifest_path = repository_root.join(CURATED_MANIFEST_PATH);
    check_manifest(&manifest_path, &canonical, &config)?;
    let report = validate_manifest(&config, &manifest).map_err(CommandError::Curation)?;
    let output = repository_root.join(output);
    let document = serde_json::to_string_pretty(&ForestProof {
        kind: "moria-product-one-forest-feasibility",
        report,
    })
    .expect("curation reports contain only serializable values");
    write(&output, format!("{document}\n"))
}

#[derive(serde::Serialize)]
struct ForestProof {
    kind: &'static str,
    report: CurationReport,
}

fn load_inputs(repository_root: &Path) -> Result<(Vec<u8>, Vec<u8>, RegionConfig), CommandError> {
    let config_path = repository_root.join(REGION_CONFIG_PATH);
    let config_bytes = read(&config_path)?;
    let config = ron::de::from_bytes(&config_bytes).map_err(|error| CommandError::Parse {
        path: config_path.display().to_string(),
        error: error.to_string(),
    })?;
    let stamp_path = repository_root.join(RUIN_STAMP_PATH);
    let stamp_bytes = read(&stamp_path)?;
    Ok((config_bytes, stamp_bytes, config))
}

fn read(path: &Path) -> Result<Vec<u8>, CommandError> {
    fs::read(path).map_err(|error| CommandError::Read {
        path: path.display().to_string(),
        error: error.to_string(),
    })
}

fn canonical_manifest_ron(manifest: &CuratedManifest) -> Result<String, CommandError> {
    let body = ron::ser::to_string_pretty(
        manifest,
        ron::ser::PrettyConfig::new()
            .depth_limit(4)
            .separate_tuple_members(true)
            .enumerate_arrays(true),
    )
    .map_err(|error| CommandError::Parse {
        path: CURATED_MANIFEST_PATH.to_owned(),
        error: error.to_string(),
    })?;
    Ok(format!("{GENERATED_FILE_COMMENT}{body}\n"))
}

fn check_manifest(
    manifest_path: &Path,
    canonical: &str,
    config: &RegionConfig,
) -> Result<(), CommandError> {
    let source = fs::read_to_string(manifest_path).map_err(|error| CommandError::Read {
        path: manifest_path.display().to_string(),
        error: error.to_string(),
    })?;
    if source != canonical {
        return Err(CommandError::NonCanonical {
            path: manifest_path.display().to_string(),
        });
    }
    let manifest: CuratedManifest =
        ron::de::from_str(&source).map_err(|error| CommandError::Parse {
            path: manifest_path.display().to_string(),
            error: error.to_string(),
        })?;
    validate_manifest(config, &manifest).map_err(CommandError::Curation)?;
    Ok(())
}

fn write(path: &Path, contents: String) -> Result<(), CommandError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| CommandError::Write {
            path: parent.display().to_string(),
            error: error.to_string(),
        })?;
    }
    fs::write(path, contents).map_err(|error| CommandError::Write {
        path: path.display().to_string(),
        error: error.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use std::path::Path;

    use super::{CommandError, run};

    #[test]
    fn check_validates_the_checked_in_manifest() {
        let repository_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        assert!(run(["check".to_owned()], &repository_root).is_ok());
    }

    #[test]
    fn rejects_unknown_commands() {
        assert!(matches!(
            run(["unknown".to_owned()], Path::new(".")),
            Err(CommandError::Usage)
        ));
    }
}
