use std::{
    collections::BTreeMap, error::Error, fmt, fs, fs::OpenOptions, io::Write, path::Path,
    process::Command,
};

use moria_world::telemetry::{
    BuildProfile, ForestFeasibilityReport, MachineProfile, ObjectIndexEvidence,
    ReportValidationError, WorstEditTargetEvidence,
};
use moria_world::{
    BiomeId, ColumnCoord, CuratedManifest, CurationError, CurationReport, ObjectKind, RegionConfig,
    RouteTag, SparseVoxelStamp, VoxelObjectShape, WorldBounds, WorldIdentity, WorldPointQ8,
    biome_at, derive_manifest, validate_manifest_with_stamp,
};
use sha2::{Digest, Sha256};

const CURATED_MANIFEST_PATH: &str = "assets/config/curated_manifest.ron";
const REGION_CONFIG_PATH: &str = "assets/config/product_one_region.ron";
const RUIN_STAMP_PATH: &str = "assets/stamps/ruin_p1.ron";
const GENERATED_FILE_COMMENT: &str = "// Generated by moria-curate generate; DO NOT EDIT.\n";

fn main() {
    if let Err(error) = run(std::env::args().skip(1), Path::new(".")) {
        eprintln!("{error}");
        std::process::exit(1);
    }
}

#[derive(Debug)]
enum CommandError {
    Usage,
    Read { path: String, error: String },
    Write { path: String, error: String },
    Parse { path: String, error: String },
    Curation(CurationError),
    Report(ReportValidationError),
    NonCanonical { path: String },
}

impl fmt::Display for CommandError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Usage => write!(
                formatter,
                "usage: moria-curate <generate|check|prove-forest --output <path>>"
            ),
            Self::Read { path, error } => write!(formatter, "failed to read {path}: {error}"),
            Self::Write { path, error } => write!(formatter, "failed to write {path}: {error}"),
            Self::Parse { path, error } => {
                write!(formatter, "failed to deserialize {path}: {error}")
            }
            Self::Curation(error) => error.fmt(formatter),
            Self::Report(error) => write!(formatter, "invalid forest feasibility report: {error}"),
            Self::NonCanonical { path } => write!(
                formatter,
                "{path} is not canonical; run moria-curate generate"
            ),
        }
    }
}

impl Error for CommandError {}

fn run(
    arguments: impl IntoIterator<Item = String>,
    repository_root: &Path,
) -> Result<(), CommandError> {
    let arguments = arguments.into_iter().collect::<Vec<_>>();
    let command = match arguments.as_slice() {
        [command] if command == "generate" || command == "check" => command.as_str(),
        [command, flag, output] if command == "prove-forest" && flag == "--output" => {
            return prove_forest(repository_root, output);
        }
        _ => return Err(CommandError::Usage),
    };
    let (config, stamp) = load_inputs(repository_root)?;
    let manifest = derive_manifest(config.seed, &config, &stamp).map_err(CommandError::Curation)?;
    let canonical = canonical_manifest_ron(&manifest)?;
    let manifest_path = repository_root.join(CURATED_MANIFEST_PATH);

    if command == "generate" {
        return write(&manifest_path, canonical);
    }
    check_manifest(&manifest_path, &canonical, &config, &stamp)
}

fn prove_forest(repository_root: &Path, output: &str) -> Result<(), CommandError> {
    let output_path = repository_root.join(output);
    if output_path.exists() {
        return Err(CommandError::Write {
            path: output_path.display().to_string(),
            error: "refusing to overwrite an existing feasibility artifact".to_owned(),
        });
    }
    let result = prove_forest_inner(repository_root, &output_path);
    if let Err(error) = result {
        write_failed_forest_artifact(&output_path, &error)?;
        return Err(error);
    }
    Ok(())
}

fn prove_forest_inner(repository_root: &Path, output: &Path) -> Result<(), CommandError> {
    let (config, stamp) = load_inputs(repository_root)?;
    let manifest = derive_manifest(config.seed, &config, &stamp).map_err(CommandError::Curation)?;
    let canonical = canonical_manifest_ron(&manifest)?;
    let manifest_path = repository_root.join(CURATED_MANIFEST_PATH);
    let curation =
        validate_manifest_with_stamp(&config, &manifest, &stamp).map_err(CommandError::Curation)?;
    let mut report = forest_report(repository_root, &config, &manifest, &curation)?;
    if let Err(error) = check_manifest(&manifest_path, &canonical, &config, &stamp) {
        report.passed = false;
        report.failure_reasons = vec![error.to_string()];
        let document = report.to_canonical_json().map_err(CommandError::Report)?;
        write_artifact(output, format!("{document}\n"))?;
        return Err(error);
    }
    if let Err(error) = report.validate() {
        report.passed = false;
        report.failure_reasons = vec![error.to_string()];
        let document =
            serde_json::to_string(&report).map_err(|_| CommandError::Report(error.clone()))?;
        write_artifact(output, format!("{document}\n"))?;
        return Err(CommandError::Report(error));
    }
    let document = report.to_canonical_json().map_err(CommandError::Report)?;
    write_artifact(output, format!("{document}\n"))
}

fn write_failed_forest_artifact(output: &Path, error: &CommandError) -> Result<(), CommandError> {
    if output.exists() {
        return Ok(());
    }
    let document = serde_json::json!({
        "schema": "moria-product-one-forest-feasibility",
        "passed": false,
        "failure_reasons": [error.to_string()],
    });
    write_artifact(output, format!("{document}\n"))
}

fn write_artifact(path: &Path, contents: String) -> Result<(), CommandError> {
    let parent = path.parent().unwrap_or_else(|| Path::new("."));
    fs::create_dir_all(parent).map_err(|error| CommandError::Write {
        path: parent.display().to_string(),
        error: error.to_string(),
    })?;
    let temporary = parent.join(format!(
        ".{}-{}-{}.tmp",
        path.file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("forest-proof"),
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map_or(0, |duration| duration.as_nanos())
    ));
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&temporary)
        .map_err(|error| CommandError::Write {
            path: temporary.display().to_string(),
            error: error.to_string(),
        })?;
    file.write_all(contents.as_bytes())
        .and_then(|()| file.sync_all())
        .map_err(|error| CommandError::Write {
            path: temporary.display().to_string(),
            error: error.to_string(),
        })?;
    fs::hard_link(&temporary, path).map_err(|error| CommandError::Write {
        path: path.display().to_string(),
        error: error.to_string(),
    })?;
    fs::remove_file(temporary).map_err(|error| CommandError::Write {
        path: path.display().to_string(),
        error: error.to_string(),
    })
}

fn forest_report(
    repository_root: &Path,
    config: &RegionConfig,
    manifest: &CuratedManifest,
    curation: &CurationReport,
) -> Result<ForestFeasibilityReport, CommandError> {
    let mut object_counts = BTreeMap::new();
    let mut species_counts = BTreeMap::new();
    let mut canopy_range_bins = BTreeMap::new();
    let mut canopy_min_q8 = None;
    let mut canopy_max_q8 = None;
    for object in &manifest.objects {
        *object_counts
            .entry(object_kind_name(object.kind).to_owned())
            .or_insert(0) += 1;
        if let Some(species) = object.species {
            *species_counts
                .entry(format!("species-{}", species.0))
                .or_insert(0) += 1;
        }
        if let moria_world::VoxelObjectShape::Tree {
            canopy_radii_q8, ..
        } = object.shape
        {
            let radius = canopy_radii_q8[0].max(canopy_radii_q8[2]);
            canopy_min_q8 = Some(canopy_min_q8.map_or(radius, |minimum: u16| minimum.min(radius)));
            canopy_max_q8 = Some(canopy_max_q8.map_or(radius, |maximum: u16| maximum.max(radius)));
            let bin = if radius <= 640 { "2m" } else { "4m" };
            *canopy_range_bins.entry(bin.to_owned()).or_insert(0) += 1;
        }
    }
    *object_counts.entry("ruin".to_owned()).or_insert(0) += 1;
    let bounds = WorldBounds::new(
        WorldPointQ8::new(
            i32::from(config.bounds.x_min_m) * 256,
            i32::from(config.bounds.y_min_m) * 256,
            i32::from(config.bounds.z_min_m) * 256,
        ),
        WorldPointQ8::new(
            i32::from(config.bounds.x_max_m) * 256,
            i32::from(config.bounds.y_max_m) * 256,
            i32::from(config.bounds.z_max_m) * 256,
        ),
    )
    .expect("validated region bounds remain non-empty");
    let forest_area_m2 =
        measured_biome_area_m2(&manifest_identity(manifest, config), BiomeId::Forest);
    let eligible_land_area_m2 =
        measured_biome_area_m2(&manifest_identity(manifest, config), BiomeId::Meadow);
    let required_object_counts =
        required_object_counts(config, forest_area_m2, eligible_land_area_m2);
    let mut failure_reasons = Vec::new();
    if curation.radius_three_target.broad_dependency_candidates
        > config.objects.max_edit_dependency_candidates
    {
        failure_reasons.push("edit dependency candidates exceed the configured limit".to_owned());
    }
    if curation.radius_three_target.exact_dependency_ids
        > u16::from(config.objects.max_affected_objects_per_edit)
    {
        failure_reasons.push("affected object count exceeds the configured limit".to_owned());
    }
    if curation.radius_three_target.dependency_bricks
        > config.objects.max_dependency_bricks_per_object
    {
        failure_reasons.push("dependency brick count exceeds the configured limit".to_owned());
    }
    for (kind, required) in &required_object_counts {
        if object_counts.get(kind).unwrap_or(&0) < required {
            failure_reasons.push(format!("missing required {kind} placements"));
        }
    }
    failure_reasons.sort();
    let passed = failure_reasons.is_empty();
    Ok(ForestFeasibilityReport {
        schema: "moria-product-one-forest-feasibility".to_owned(),
        timestamp_utc: command_output("date", ["-u", "+%Y-%m-%dT%H:%M:%SZ"])
            .unwrap_or_else(|_| "1970-01-01T00:00:00Z".to_owned()),
        passed,
        failure_reasons,
        build: BuildProfile {
            cargo_profile: cargo_profile_name().to_owned(),
            git_commit: command_output(
                "git",
                [
                    "-C",
                    repository_root.to_str().unwrap_or("."),
                    "rev-parse",
                    "HEAD",
                ],
            )
            .unwrap_or_else(|_| "0".repeat(40)),
            rustc_version: command_output("rustc", ["--version"])
                .unwrap_or_else(|_| "unknown".to_owned()),
        },
        world: WorldIdentity::new(manifest.seed, manifest.parameters_digest, bounds),
        manifest_sha256: hex_sha256(canonical_manifest_ron(manifest)?.as_bytes()),
        machine: acceptance_machine_profile().unwrap_or_else(|_| incomplete_machine_profile()),
        forest_area_m2,
        eligible_land_area_m2,
        required_object_counts,
        object_counts,
        species_counts,
        minimum_tree_spacing_q8: minimum_tree_spacing_q8(manifest),
        canopy_min_q8: canopy_min_q8.unwrap_or(0),
        canopy_max_q8: canopy_max_q8.unwrap_or(0),
        canopy_range_bins,
        minimum_route_clearance_q8: minimum_route_clearance_q8(manifest),
        overlap_conflicts: 0,
        first_conflict: None,
        object_index: ObjectIndexEvidence {
            validation_ms: (curation.object_index_validation_us as f64 / 1_000.0)
                .max(f64::MIN_POSITIVE),
            build_ms: (curation.object_index_build_us as f64 / 1_000.0).max(f64::MIN_POSITIVE),
            retained_bytes: curation.retained_index_bytes,
            retained_byte_categories: BTreeMap::from([(
                "object-index".to_owned(),
                curation.retained_index_bytes,
            )]),
            placement_records: curation.placement_count,
            dependency_grid_entries: curation.dependency_grid_entries,
            sample_grid_entries: curation.sample_grid_entries,
            max_dependency_cell_entries: curation.max_dependency_cell_entries,
            max_sample_cell_entries: curation.max_sample_cell_entries,
            max_horizon_tree_members_per_cell: curation.max_horizon_tree_members_per_cell,
            max_edit_candidates: curation.radius_three_target.broad_dependency_candidates,
            max_edit_affected_objects: u8::try_from(
                curation.radius_three_target.exact_dependency_ids,
            )
            .unwrap_or(u8::MAX),
            max_dependency_bricks: curation.max_dependency_bricks,
            dependency_coordinate_allocation_bytes: curation.dependency_coordinate_allocation_bytes,
        },
        worst_edit_target: WorstEditTargetEvidence {
            center: WorldPointQ8::new(
                curation.radius_three_target.center.x * 64,
                curation.radius_three_target.center.y * 64,
                curation.radius_three_target.center.z * 64,
            ),
            broad_candidates: curation.radius_three_target.broad_dependency_candidates,
            exact_dependency_ids: curation.radius_three_target.exact_dependency_ids,
            dependency_bricks: curation.radius_three_target.dependency_bricks,
            tie_break_rank: 0,
        },
    })
}

const fn cargo_profile_name() -> &'static str {
    if cfg!(debug_assertions) {
        "debug"
    } else {
        "release"
    }
}

fn manifest_identity(manifest: &CuratedManifest, config: &RegionConfig) -> WorldIdentity {
    WorldIdentity::new(
        manifest.seed,
        manifest.parameters_digest,
        WorldBounds::new(
            WorldPointQ8::new(
                i32::from(config.bounds.x_min_m) * 256,
                i32::from(config.bounds.y_min_m) * 256,
                i32::from(config.bounds.z_min_m) * 256,
            ),
            WorldPointQ8::new(
                i32::from(config.bounds.x_max_m) * 256,
                i32::from(config.bounds.y_max_m) * 256,
                i32::from(config.bounds.z_max_m) * 256,
            ),
        )
        .expect("validated region bounds remain non-empty"),
    )
}

fn measured_biome_area_m2(identity: &WorldIdentity, biome: BiomeId) -> u32 {
    let mut cells = 0_u32;
    for x_m in (identity.bounds.min().x.div_euclid(256)
        ..identity.bounds.max_exclusive().x.div_euclid(256))
        .step_by(4)
    {
        for z_m in (identity.bounds.min().z.div_euclid(256)
            ..identity.bounds.max_exclusive().z.div_euclid(256))
            .step_by(4)
        {
            if biome_at(
                identity,
                ColumnCoord {
                    x: x_m * 4,
                    z: z_m * 4,
                },
            ) == biome
            {
                cells += 1;
            }
        }
    }
    cells * 16
}

fn required_object_counts(
    config: &RegionConfig,
    forest_area_m2: u32,
    eligible_land_area_m2: u32,
) -> BTreeMap<String, u32> {
    let trees = forest_area_m2.div_ceil(25);
    let birch = u32::from(config.biome.tree_species_mix_percent[0]) * trees / 100;
    BTreeMap::from([
        ("tree-a".to_owned(), birch),
        ("tree-b".to_owned(), trees - birch),
        (
            "bush".to_owned(),
            (forest_area_m2 * u32::from(config.biome.bushes_per_hectare)).div_ceil(10_000),
        ),
        (
            "boulder".to_owned(),
            (eligible_land_area_m2 * u32::from(config.objects.boulders_per_hectare))
                .div_ceil(10_000),
        ),
        (
            "stump".to_owned(),
            (eligible_land_area_m2 * u32::from(config.objects.stumps_per_hectare)).div_ceil(10_000),
        ),
        (
            "rock".to_owned(),
            (eligible_land_area_m2 * u32::from(config.objects.rocks_per_hectare)).div_ceil(10_000),
        ),
        ("ruin".to_owned(), 1),
    ])
}

fn object_kind_name(kind: ObjectKind) -> &'static str {
    match kind {
        ObjectKind::TreeA => "tree-a",
        ObjectKind::TreeB => "tree-b",
        ObjectKind::Bush => "bush",
        ObjectKind::Boulder => "boulder",
        ObjectKind::Stump => "stump",
        ObjectKind::Rock => "rock",
        ObjectKind::Ruin => "ruin",
    }
}

fn minimum_tree_spacing_q8(manifest: &CuratedManifest) -> u32 {
    let trees = manifest
        .objects
        .iter()
        .filter(|placement| matches!(placement.kind, ObjectKind::TreeA | ObjectKind::TreeB))
        .collect::<Vec<_>>();
    trees
        .iter()
        .enumerate()
        .flat_map(|(index, left)| trees[index + 1..].iter().map(move |right| (*left, *right)))
        .map(|(left, right)| {
            horizontal_distance_q8(left.transform_q.translation, right.transform_q.translation)
        })
        .min()
        .unwrap_or(0)
}

fn minimum_route_clearance_q8(manifest: &CuratedManifest) -> u32 {
    manifest
        .route
        .windows(2)
        .filter(|segment| {
            segment
                .iter()
                .all(|waypoint| waypoint.tags.contains(&RouteTag::Forest))
        })
        .flat_map(|segment| {
            manifest.objects.iter().map(move |placement| {
                point_segment_distance_q8(
                    placement.transform_q.translation,
                    segment[0].point,
                    segment[1].point,
                )
                .saturating_sub(horizontal_radius_q8(&placement.shape))
            })
        })
        .min()
        .unwrap_or(0)
}

fn horizontal_radius_q8(shape: &VoxelObjectShape) -> u32 {
    match shape {
        VoxelObjectShape::Tree {
            canopy_radii_q8, ..
        }
        | VoxelObjectShape::Bush {
            radii_q8: canopy_radii_q8,
        }
        | VoxelObjectShape::Boulder {
            radii_q8: canopy_radii_q8,
            ..
        }
        | VoxelObjectShape::Rock {
            radii_q8: canopy_radii_q8,
            ..
        } => u32::from(canopy_radii_q8[0].max(canopy_radii_q8[2])),
        VoxelObjectShape::Stump { radius_q8, .. } => u32::from(*radius_q8),
        VoxelObjectShape::SparseStamp { .. } => 0,
    }
}

fn horizontal_distance_q8(left: WorldPointQ8, right: WorldPointQ8) -> u32 {
    integer_sqrt(
        i64::from(left.x - right.x).pow(2) as u64 + i64::from(left.z - right.z).pow(2) as u64,
    )
}

fn point_segment_distance_q8(point: WorldPointQ8, start: WorldPointQ8, end: WorldPointQ8) -> u32 {
    let dx = i128::from(end.x - start.x);
    let dz = i128::from(end.z - start.z);
    let px = i128::from(point.x - start.x);
    let pz = i128::from(point.z - start.z);
    let length_squared = dx * dx + dz * dz;
    if length_squared == 0 {
        return horizontal_distance_q8(point, start);
    }
    let projection = (px * dx + pz * dz).clamp(0, length_squared);
    let nearest_x_numerator = i128::from(start.x) * length_squared + dx * projection;
    let nearest_z_numerator = i128::from(start.z) * length_squared + dz * projection;
    let distance_x_numerator = i128::from(point.x) * length_squared - nearest_x_numerator;
    let distance_z_numerator = i128::from(point.z) * length_squared - nearest_z_numerator;
    integer_sqrt(
        ((distance_x_numerator * distance_x_numerator
            + distance_z_numerator * distance_z_numerator)
            / length_squared.pow(2)) as u64,
    )
}

fn integer_sqrt(value: u64) -> u32 {
    let mut root = value;
    let mut next = root.div_ceil(2);
    while next < root {
        root = next;
        next = (root + value / root) / 2;
    }
    u32::try_from(root).unwrap_or(u32::MAX)
}

fn command_output<const N: usize>(program: &str, arguments: [&str; N]) -> Result<String, ()> {
    let output = Command::new(program)
        .args(arguments)
        .output()
        .map_err(|_| ())?;
    output
        .status
        .success()
        .then(|| String::from_utf8_lossy(&output.stdout).trim().to_owned())
        .ok_or(())
}

fn hex_sha256(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn incomplete_machine_profile() -> MachineProfile {
    let os_name = std::env::consts::OS.to_owned();
    let architecture = std::env::consts::ARCH.to_owned();
    let profile_id_sha256 = hex_sha256(format!("{os_name}|{architecture}").as_bytes());
    MachineProfile {
        profile_id_sha256,
        os_name,
        os_version: "unavailable".to_owned(),
        architecture,
        cpu_model: "unavailable".to_owned(),
        logical_cores: 1,
        total_physical_memory_bytes: 1,
        gpu_adapter_name: "unavailable".to_owned(),
        gpu_vendor: 0,
        gpu_device: 0,
        gpu_device_class: "unavailable".to_owned(),
        wgpu_backend: "unavailable".to_owned(),
        driver: None,
        driver_metadata_available: false,
        memory_architecture: "unavailable".to_owned(),
        acceptance_label: "unavailable".to_owned(),
    }
}

#[cfg(test)]
fn acceptance_machine_profile() -> Result<MachineProfile, CommandError> {
    Ok(MachineProfile {
        profile_id_sha256: hex_sha256(b"moria-curate-test-acceptance-machine"),
        os_name: "macOS".to_owned(),
        os_version: "15".to_owned(),
        architecture: "aarch64".to_owned(),
        cpu_model: "Apple M4".to_owned(),
        logical_cores: 10,
        total_physical_memory_bytes: 32 * 1024 * 1024 * 1024,
        gpu_adapter_name: "Apple M4".to_owned(),
        gpu_vendor: 0,
        gpu_device: 0,
        gpu_device_class: "integrated".to_owned(),
        wgpu_backend: "metal".to_owned(),
        driver: None,
        driver_metadata_available: false,
        memory_architecture: "unified".to_owned(),
        acceptance_label: "m4-mac-mini-32gb".to_owned(),
    })
}

#[cfg(not(test))]
fn acceptance_machine_profile() -> Result<MachineProfile, CommandError> {
    if std::env::consts::OS != "macos" || std::env::consts::ARCH != "aarch64" {
        return Err(CommandError::Report(ReportValidationError::Identity {
            field: "M4 machine",
        }));
    }
    let os_version = command_output("sw_vers", ["-productVersion"])
        .map_err(|_| CommandError::Report(ReportValidationError::Identity { field: "machine" }))?;
    let cpu_model = command_output("sysctl", ["-n", "machdep.cpu.brand_string"])
        .map_err(|_| CommandError::Report(ReportValidationError::Identity { field: "machine" }))?;
    let model = command_output("sysctl", ["-n", "hw.model"])
        .map_err(|_| CommandError::Report(ReportValidationError::Identity { field: "machine" }))?;
    let logical_cores = command_output("sysctl", ["-n", "hw.logicalcpu"])
        .ok()
        .and_then(|value| value.parse().ok())
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "machine",
        }))?;
    let total_physical_memory_bytes = command_output("sysctl", ["-n", "hw.memsize"])
        .ok()
        .and_then(|value| value.parse().ok())
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "machine",
        }))?;
    let display_profile = command_output("system_profiler", ["SPDisplaysDataType", "-json"])
        .map_err(|_| CommandError::Report(ReportValidationError::Identity { field: "gpu" }))?;
    let (
        gpu_adapter_name,
        gpu_vendor,
        gpu_device,
        gpu_device_class,
        wgpu_backend,
        memory_architecture,
    ) = display_profile_fields(&display_profile)?;
    if model != "Mac16,10" || cpu_model != "Apple M4" {
        return Err(CommandError::Report(ReportValidationError::Identity {
            field: "M4 machine",
        }));
    }
    Ok(MachineProfile {
        profile_id_sha256: hex_sha256(
            format!(
                "macOS|{os_version}|{model}|{cpu_model}|{logical_cores}|{total_physical_memory_bytes}|{gpu_adapter_name}|{gpu_vendor}|{gpu_device}|{gpu_device_class}|{wgpu_backend}|{memory_architecture}"
            )
            .as_bytes(),
        ),
        os_name: "macOS".to_owned(),
        os_version,
        architecture: "aarch64".to_owned(),
        cpu_model: cpu_model.clone(),
        logical_cores,
        total_physical_memory_bytes,
        gpu_adapter_name,
        gpu_vendor,
        gpu_device,
        gpu_device_class,
        wgpu_backend,
        driver: None,
        driver_metadata_available: false,
        memory_architecture,
        acceptance_label: "m4-mac-mini-32gb".to_owned(),
    })
}

#[cfg(not(test))]
fn display_profile_fields(
    document: &str,
) -> Result<(String, u32, u32, String, String, String), CommandError> {
    let displays: serde_json::Value = serde_json::from_str(document)
        .map_err(|_| CommandError::Report(ReportValidationError::Identity { field: "gpu" }))?;
    let display = displays
        .get("SPDisplaysDataType")
        .and_then(serde_json::Value::as_array)
        .and_then(|entries| entries.first())
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "gpu",
        }))?;
    let adapter = display
        .get("sppci_model")
        .and_then(serde_json::Value::as_str)
        .filter(|value| !value.is_empty())
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "gpu",
        }))?
        .to_owned();
    let vendor = display
        .get("spdisplays_vendor")
        .and_then(serde_json::Value::as_str)
        .and_then(hex_identifier)
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "gpu",
        }))?;
    let device = display
        .get("spdisplays_device-id")
        .and_then(serde_json::Value::as_str)
        .and_then(hex_identifier)
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "gpu",
        }))?;
    let backend = display
        .get("spdisplays_metal")
        .and_then(serde_json::Value::as_str)
        .filter(|value| value.contains("Metal"))
        .map(|_| "metal".to_owned())
        .ok_or(CommandError::Report(ReportValidationError::Identity {
            field: "gpu",
        }))?;
    Ok((
        adapter,
        vendor,
        device,
        "integrated".to_owned(),
        backend,
        "unified".to_owned(),
    ))
}

#[cfg(not(test))]
fn hex_identifier(value: &str) -> Option<u32> {
    let digits = value
        .split_whitespace()
        .find_map(|piece| piece.strip_prefix("0x"))?;
    u32::from_str_radix(digits, 16).ok()
}

fn load_inputs(repository_root: &Path) -> Result<(RegionConfig, SparseVoxelStamp), CommandError> {
    let config_path = repository_root.join(REGION_CONFIG_PATH);
    let config_bytes = read(&config_path)?;
    let config = ron::de::from_bytes(&config_bytes).map_err(|error| CommandError::Parse {
        path: config_path.display().to_string(),
        error: error.to_string(),
    })?;
    let stamp_path = repository_root.join(RUIN_STAMP_PATH);
    let stamp_bytes = read(&stamp_path)?;
    let stamp = ron::de::from_bytes(&stamp_bytes).map_err(|error| CommandError::Parse {
        path: stamp_path.display().to_string(),
        error: error.to_string(),
    })?;
    Ok((config, stamp))
}

fn read(path: &Path) -> Result<Vec<u8>, CommandError> {
    fs::read(path).map_err(|error| CommandError::Read {
        path: path.display().to_string(),
        error: error.to_string(),
    })
}

fn canonical_manifest_ron(manifest: &CuratedManifest) -> Result<String, CommandError> {
    let body = ron::ser::to_string_pretty(
        manifest,
        ron::ser::PrettyConfig::new()
            .depth_limit(4)
            .separate_tuple_members(true)
            .enumerate_arrays(true),
    )
    .map_err(|error| CommandError::Parse {
        path: CURATED_MANIFEST_PATH.to_owned(),
        error: error.to_string(),
    })?;
    Ok(format!("{GENERATED_FILE_COMMENT}{body}\n"))
}

fn check_manifest(
    manifest_path: &Path,
    canonical: &str,
    config: &RegionConfig,
    stamp: &SparseVoxelStamp,
) -> Result<(), CommandError> {
    let source = fs::read_to_string(manifest_path).map_err(|error| CommandError::Read {
        path: manifest_path.display().to_string(),
        error: error.to_string(),
    })?;
    if source != canonical {
        return Err(CommandError::NonCanonical {
            path: manifest_path.display().to_string(),
        });
    }
    let manifest: CuratedManifest =
        ron::de::from_str(&source).map_err(|error| CommandError::Parse {
            path: manifest_path.display().to_string(),
            error: error.to_string(),
        })?;
    validate_manifest_with_stamp(config, &manifest, stamp).map_err(CommandError::Curation)?;
    Ok(())
}

fn write(path: &Path, contents: String) -> Result<(), CommandError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| CommandError::Write {
            path: parent.display().to_string(),
            error: error.to_string(),
        })?;
    }
    fs::write(path, contents).map_err(|error| CommandError::Write {
        path: path.display().to_string(),
        error: error.to_string(),
    })
}

#[cfg(test)]
mod tests {
    use std::{fs, path::Path};

    use moria_world::telemetry::ForestFeasibilityReport;

    use super::{CommandError, run, write_artifact};

    #[test]
    fn check_validates_the_checked_in_manifest() {
        let repository_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        assert!(run(["check".to_owned()], &repository_root).is_ok());
    }

    #[test]
    fn rejects_unknown_commands() {
        assert!(matches!(
            run(["unknown".to_owned()], Path::new(".")),
            Err(CommandError::Usage)
        ));
    }

    #[test]
    fn prove_forest_counts_the_separate_ruin_placement() {
        let repository_root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        let output = std::env::temp_dir().join(format!(
            "moria-curate-forest-proof-{}.json",
            std::process::id()
        ));
        let relative_output = output.to_str().unwrap().to_owned();

        assert!(
            run(
                [
                    "prove-forest".to_owned(),
                    "--output".to_owned(),
                    relative_output,
                ],
                &repository_root,
            )
            .is_err()
        );

        let proof: ForestFeasibilityReport =
            serde_json::from_slice(&fs::read(&output).unwrap()).unwrap();
        assert!(!proof.passed);
        assert_eq!(proof.object_counts.get("ruin"), Some(&1));
        assert_eq!(proof.required_object_counts.get("ruin"), Some(&1));
        proof.validate().unwrap();
        fs::remove_file(output).unwrap();
    }

    #[test]
    fn feasibility_artifacts_do_not_overwrite_preserved_failures() {
        let output = std::env::temp_dir().join(format!(
            "moria-curate-preserved-failure-{}.json",
            std::process::id()
        ));
        fs::write(&output, b"preserved failure\n").unwrap();

        assert!(write_artifact(&output, "replacement\n".to_owned()).is_err());
        assert_eq!(fs::read(&output).unwrap(), b"preserved failure\n");
        fs::remove_file(output).unwrap();
    }
}
